# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f0d5d4da67dd2151ea0cdf459d35a26ff40407e585295dd81563dfa55e8a2c1be030f6707047d87fd783e3ada71fa38930028cb388a5ea964861cd85cd6348e

test:
  secret_key_base: d527e678e5b9a1a1a51bdb3bb6e2bea441edf6ad18037119ec1b9bf0ca5e281289bb5ea9482bae7908e5f0f020413f9c24cc9d629b6d42b4f88cce2ea408ead3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
